In [1]:
# import pandas as pd
#
# # Đọc file JSON dạng array
# df = pd.read_json("data/law_content_chunks.json")
#
# # Ghi ra file Parquet
# df.to_parquet("data/law_html_content.parquet",
#     index=False,
#     compression="zstd",
#     engine="pyarrow"
# )

In [1]:
import json

import pandas as pd

df_raw = pd.read_parquet("data/law_html_content.parquet", engine="pyarrow")

df_raw.head(3)

,law_id,url,content_html,chunks,error
0,14/2022/TT-NHNN,https://thuvienphapluat.vn/van-ban/Tien-te-Nga...,"\r\n<!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 4....",[{'content': 'NGÂN HÀNG NHÀ NƯỚC VIỆT NAM -...,None
1,11/2022/TT-NHNN,https://thuvienphapluat.vn/van-ban/Tien-te-Nga...,"\r\n<!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 4....",[{'content': 'NGÂN HÀNG NHÀ NƯỚC VIỆT NAM -...,None
2,02/2007/TT-BNV,https://thuvienphapluat.vn/van-ban/Lao-dong-Ti...,"\r\n<!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 4....",[{'content': 'BỘ NỘI VỤ ****** CỘNG HOÀ ...,None

In [2]:
import numpy as np

df = df_raw.copy()
df = df[df['chunks'].apply(lambda x: len(x) == 0)]
print(len(df))
df.head(3)

171

,law_id,url,content_html,chunks,error
3,17/2019/TT-NHNN,https://thuvienphapluat.vn/van-ban/Tien-te-Nga...,"\r\n<!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 4....",[],None
70,123/2020/NĐ-CP,https://thuvienphapluat.vn/van-ban/Ke-toan-Kie...,"\r\n<!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 4....",[],None
139,04/2020/TT-BTP,https://thuvienphapluat.vn/van-ban/Quyen-dan-s...,"\r\n<!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 4....",[],None

In [4]:
# df_raw['chunks'] = df_raw['chunks'].apply(lambda x: x.tolist() if isinstance(x, np.ndarray) else x)
# chunks = df_raw["chunks"][0]
# for chunk in chunks:
#     print(" - ".join(chunk["titles"]))
#     print(chunk["content"])
#     print("-"*50)

In [5]:
from bs4 import BeautifulSoup

def get_deepest(div, depth=0, max_depth=2):
    # Nếu đạt tới độ sâu tối đa thì dừng
    if depth >= max_depth:
        return div

    # Tìm các div con trực tiếp
    child_divs = div.find_all('div', recursive=False)
    if not child_divs:
        return div

    # Đệ quy vào div con đầu tiên
    return get_deepest(child_divs[0], depth + 1, max_depth)

def chunk_document(html):
    soup = BeautifulSoup(html, 'html.parser')
    container = soup.find('div', class_='content1')
    if not container:
        return []

    container = get_deepest(container)

    # Định nghĩa thứ tự các cấp tiêu đề
    levels   = ['loai', 'chuong', 'muc', 'dieu']
    current  = { lvl: None for lvl in levels }
    chunks   = []
    buffer   = []

    def close_chunk():
        # Chỉ đóng chunk khi đã gặp loai_… (seen_loai) và buffer không rỗng
        if buffer:
            titles = [current[l] for l in levels if current[l]]
            chunks.append({
                'titles': titles,
                'content': '\n'.join(buffer).strip()
            })
        buffer.clear()

    for tag in container.find_all(recursive=False):
        check_flag = False
        first_a = tag.find('a')
        if first_a and first_a.has_attr('name'):
            # Nếu thẻ <a> có thuộc tính name, thì đó là tiêu đề
            name = first_a['name']
            for lvl in levels:
                if name.startswith(lvl):
                    check_flag = True
                    if name.endswith("_name"):
                        if current[lvl] is None:
                            current[lvl] = first_a.get_text(strip=True)
                        else:
                            current[lvl] += " " + first_a.get_text(strip=True)
                    else:
                        close_chunk()
                        idx = levels.index(lvl)
                        # reset các cấp thấp hơn
                        for lower in levels[idx+1:]:
                            current[lower] = None
                        # lấy text làm title
                        current[lvl]  = first_a.get_text(strip=True)
                        break
            if not check_flag:
                text = tag.get_text(separator=' ', strip=True)
                if text:
                    buffer.append(text)
        else:
            text = tag.get_text(separator=' ', strip=True)
            if text:
                buffer.append(text)
    close_chunk()
    return chunks

html_content = df_raw["content_html"][9].strip()
# html_content = df_raw["content_html"][0].strip()
chunks = chunk_document(html_content)
print(chunks)

[{'titles': [], 'content': 'QUỐC HỘI ------- CỘNG HÒA XÃ HỘI CHỦ\r\n  NGHĨA VIỆT NAM Độc lập – Tự do – Hạnh phúc --------- Luật số:\r\n  47/2010/QH12 Hà Nội, ngày 16\r\n  tháng 6 năm 2010'}, {'titles': ['LUẬT CÁC TỔ CHỨC\r\nTÍN DỤNG'], 'content': 'Căn cứ Hiến\r\npháp nước Cộng hòa xã hội chủ nghĩa Việt Nam năm 1992 đã được sửa đổi, bổ\r\nsung một số điều theo Nghị quyết số 51/2001/QH10 ;\nQuốc hội ban hành Luật các tổ chức tín dụng.'}, {'titles': ['LUẬT CÁC TỔ CHỨC\r\nTÍN DỤNG', 'Chương I NHỮNG\r\nQUY ĐỊNH CHUNG', 'Điều 1. Phạm vi điều\r\nchỉnh'], 'content': 'Luật này quy định về việc thành lập, tổ chức,\r\nhoạt động, kiểm soát đặc biệt, tổ chức lại, giải thể tổ chức tín dụng; việc\r\nthành lập, tổ chức, hoạt động của chi nhánh ngân hàng nước ngoài, văn phòng đại\r\ndiện của tổ chức tín dụng nước ngoài, tổ chức nước ngoài khác có hoạt động ngân\r\nhàng.'}, {'titles': ['LUẬT CÁC TỔ CHỨC\r\nTÍN DỤNG', 'Chương I NHỮNG\r\nQUY ĐỊNH CHUNG', 'Điều 2. Đối tượng áp\r\ndụng'], 'content': 'Luật này áp dụng đối với các đối tượng sau\r\nđây:\n1. Tổ chức tín dụng;\n2. Chi nhánh ngân hàng nước ngoài;\n3. Văn phòng đại diện của tổ chức tín dụng nước\r\nngoài, tổ chức nước ngoài khác có hoạt động ngân hàng;\n4. Tổ chức, cá nhân có liên quan đến việc\r\nthành lập, tổ chức, hoạt động, kiểm soát đặc biệt, tổ chức lại, giải thể tổ chức\r\ntín dụng; việc thành lập, tổ chức, hoạt động của chi nhánh ngân hàng nước\r\nngoài, văn phòng đại diện của tổ chức tín dụng nước ngoài, tổ chức nước ngoài\r\nkhác có hoạt động ngân hàng.'}, {'titles': ['LUẬT CÁC TỔ CHỨC\r\nTÍN DỤNG', 'Chương I NHỮNG\r\nQUY ĐỊNH CHUNG', 'Điều 3. Áp dụng Luật\r\ncác tổ chức tín dụng, điều ước quốc tế, tập quán thương mại quốc tế và các luật\r\ncó liên quan'], 'content': '1. Việc thành lập, tổ chức và hoạt động, kiểm\r\nsoát đặc biệt, tổ chức lại, giải thể tổ chức tín dụng; việc thành lập, tổ chức\r\nvà hoạt động của chi nhánh ngân hàng nước ngoài, văn phòng đại diện của tổ chức\r\ntín dụng nước ngoài, tổ chức nước ngoài khác có hoạt động ngân hàng phải tuân\r\ntheo quy định của Luật này và các quy định khác của pháp luật có liên quan.\n2. Trường hợp có quy định khác nhau giữa Luật\r\nnày và các luật khác có liên quan về thành lập, tổ chức, hoạt động, kiểm soát đặc\r\nbiệt, tổ chức lại, giải thể tổ chức tín dụng; việc thành lập, tổ chức, hoạt động\r\ncủa chi nhánh ngân hàng nước ngoài, văn phòng đại diện của tổ chức tín dụng nước\r\nngoài, tổ chức nước ngoài khác có hoạt động ngân hàng thì áp dụng theo quy định\r\ncủa Luật này.\n3. Trường hợp điều ước quốc tế mà Cộng hòa xã\r\nhội chủ nghĩa Việt Nam là thành viên có quy định khác với quy định của Luật này\r\nthì áp dụng quy định của điều ước quốc tế đó.\n4. Tổ chức, cá nhân\r\ntham gia hoạt động ngân hàng được quyền thỏa thuận áp dụng tập quán thương mại,\r\nbao gồm:\na) Tập quán thương mại quốc tế do Phòng\r\nthương mại quốc tế ban hành;\nb) Tập quán thương mại khác không trái với\r\npháp luật của Việt Nam.'}, {'titles': ['LUẬT CÁC TỔ CHỨC\r\nTÍN DỤNG', 'Chương I NHỮNG\r\nQUY ĐỊNH CHUNG', 'Điều 4. Giải thích từ\r\nngữ'], 'content': 'Trong Luật này, các từ ngữ dưới đây được hiểu\r\nnhư sau:\n1. Tổ chức tín dụng là doanh nghiệp thực hiện một, một số hoặc tất cả các hoạt động ngân hàng. Tổ\r\nchức tín dụng bao gồm ngân hàng, tổ chức tín dụng phi ngân hàng, tổ chức tài\r\nchính vi mô và quỹ tín dụng nhân dân.\n2. Ngân hàng là loại hình tổ chức tín\r\ndụng có thể được thực hiện tất cả các hoạt động ngân hàng theo quy định của Luật\r\nnày. Theo tính chất và mục tiêu hoạt động, các loại hình ngân hàng bao gồm ngân\r\nhàng thương mại, ngân hàng chính sách, ngân hàng hợp tác xã.\n3. Ngân hàng thương mại là loại hình\r\nngân hàng được thực hiện tất cả các hoạt động ngân hàng và các hoạt động kinh\r\ndoanh khác theo quy định của Luật này nhằm mục tiêu lợi nhuận.\n4. Tổ chức tín dụng\r\nphi ngân hàng là loại hình tổ chức tín dụng được thực hiện một hoặc một số\r\nhoạt động ngân hàng theo quy định của Luật này, trừ các hoạt động nhận tiền gửi\r\ncủa cá nhân và cung ứng các dịch vụ thanh toán qua tài khoản của khách hàng. Tổ\r\nchức tín dụng phi ngân hàng bao gồm công ty tài chính, công ty cho thuê tài\r\nchính và các tổ chức tín dụng phi ngân hàng khác.\nCông ty cho thuê tài chính là loại hình công\r\nty tài chính có hoạt động chính là cho thuê tài chính theo quy định của Luật\r\nnày.\n5. Tổ chức tài\r\nchính vi mô là loại hình tổ chức tín dụng chủ yếu thực hiện một số hoạt động\r\nngân hàng nhằm đáp ứng nhu cầu của các cá nhân, hộ gia đình có thu nhập thấp và\r\ndoanh nghiệp siêu nhỏ.\n6. Quỹ tín dụng\r\nnhân dân là tổ chức tín dụng do các pháp nhân, cá nhân và hộ gia đình tự\r\nnguyện thành lập dưới hình thức hợp tác xã để thực hiện một số hoạt động ngân\r\nhàng theo quy định của Luật này và Luật hợp tác xã nhằm\r\nmục tiêu chủ yếu là tương trợ nhau phát triển sản xuất, kinh doanh và đời sống.\n7. Ngân hàng hợp tác xã là ngân hàng của\r\ntất cả các quỹ tín dụng nhân dân do các quỹ tín dụng nhân dân và một số pháp\r\nnhân góp vốn thành lập theo quy định của Luật này nhằm mục tiêu chủ yếu là liên\r\nkết hệ thống, hỗ trợ tài chính, điều hòa vốn trong hệ thống các quỹ tín dụng\r\nnhân dân.\n8. Tổ chức tín dụng nước ngoài là tổ\r\nchức tín dụng được thành lập ở nước ngoài theo quy định của pháp luật nước\r\nngoài.\nTổ chức tín dụng nước ngoài được hiện diện\r\nthương mại tại Việt Nam dưới hình thức văn phòng đại diện, ngân hàng liên\r\ndoanh, ngân hàng 100% vốn nước ngoài, chi nhánh ngân hàng nước ngoài, công ty\r\ntài chính liên doanh, công ty tài chính 100% vốn nước ngoài, công ty cho thuê\r\ntài chính liên doanh, công ty cho thuê tài chính 100% vốn nước ngoài.\nNgân hàng liên doanh, ngân hàng 100% vốn nước\r\nngoài là loại hình ngân hàng thương mại; công ty tài chính liên doanh, công ty\r\ntài chính 100% vốn nước ngoài là loại hình công ty tài chính; công ty cho thuê\r\ntài chính liên doanh, công ty cho thuê tài chính 100% vốn nước ngoài là loại\r\nhình công ty cho thuê tài chính theo quy định của Luật này.\n9. Chi nhánh ngân\r\nhàng nước ngoài là đơn vị phụ thuộc của ngân hàng nước ngoài, không có tư\r\ncách pháp nhân, được ngân hàng nước ngoài bảo đảm chịu trách nhiệm về mọi nghĩa\r\nvụ, cam kết của chi nhánh tại Việt Nam.\n10. Vốn tự có gồm giá trị thực của vốn điều lệ của tổ chức tín dụng hoặc vốn được cấp của chi\r\nnhánh ngân hàng nước ngoài và các quỹ dự trữ, một số tài sản nợ khác theo quy định\r\ncủa Ngân hàng Nhà nước Việt Nam (sau đây gọi là Ngân hàng Nhà nước).\n11. Giấy phép bao gồm Giấy phép thành lập và hoạt động của tổ chức tín dụng, Giấy phép thành\r\nlập chi nhánh ngân hàng nước ngoài, Giấy phép thành lập văn phòng đại diện của\r\ntổ chức tín dụng nước ngoài, tổ chức nước ngoài khác có hoạt động ngân hàng do\r\nNgân hàng Nhà nước cấp. Văn bản của Ngân hàng Nhà nước về sửa đổi, bổ sung Giấy\r\nphép là một bộ phận không tách rời của Giấy phép.\n12. Hoạt động ngân\r\nhàng là việc kinh doanh, cung ứng thường xuyên một hoặc một số các nghiệp vụ\r\nsau đây:\na) Nhận tiền gửi;\nb) Cấp tín dụng;\nc) Cung ứng dịch vụ thanh toán qua tài khoản.\n13. Nhận tiền gửi là hoạt động nhận tiền của tổ chức, cá nhân dưới hình thức tiền gửi không kỳ hạn,\r\ntiền gửi có kỳ hạn, tiền gửi tiết kiệm, phát hành chứng chỉ tiền gửi, kỳ phiếu,\r\ntín phiếu và các hình thức nhận tiền gửi khác theo nguyên tắc có hoàn trả đầy đủ\r\ntiền gốc, lãi cho người gửi tiền theo thỏa thuận.\n14. Cấp tín dụng là việc thỏa thuận để tổ chức, cá nhân sử dụng một khoản tiền hoặc cam kết cho\r\nphép sử dụng một khoản tiền theo nguyên tắc có hoàn trả bằng nghiệp vụ cho vay,\r\nchiết khấu, cho thuê tài chính, bao thanh toán, bảo lãnh ngân hàng và các nghiệp\r\nvụ cấp tín dụng khác.\n15. Cung ứng dịch\r\nvụ thanh toán qua tài khoản là việc cung ứng phương tiện thanh toán; thực\r\nhiện dịch vụ thanh toán séc, lệnh chi, ủy nhiệm chi, nhờ thu, ủy nhiệm thu, thẻ\r\nngân hàng, thư tín dụng và các dịch vụ thanh toán khác cho khách hàng thông qua\r\ntài khoản của khách hàng.\n16. Cho vay là\r\nhình thức cấp tín dụng, theo đó bên cho vay giao hoặc cam kết giao cho khách\r\nhàng một khoản tiền để sử dụng vào mục đích xác định trong một thời gian nhất định\r\ntheo thỏa thuận với nguyên tắc có hoàn trả cả gốc và lãi.\n17. Bao thanh toán là hình thức cấp\r\ntín dụng cho bên bán hàng hoặc bên mua hàng thông qua việc mua lại có bảo lưu\r\nquyền truy đòi các khoản phải thu hoặc các khoản phải trả phát sinh từ việc\r\nmua, bán hàng hoá, cung ứng dịch vụ theo hợp đồng mua, bán hàng hoá, cung ứng dịch\r\nvụ.\n18. Bảo lãnh ngân\r\nhàng là hình thức cấp tín dụng, theo đó tổ chức tín dụng cam kết với bên nhận\r\nbảo lãnh về việc tổ chức tín dụng sẽ thực hiện nghĩa vụ tài chính thay cho\r\nkhách hàng khi khách hàng không thực hiện hoặc thực hiện không đầy đủ nghĩa vụ\r\nđã cam kết; khách hàng phải nhận nợ và hoàn trả cho tổ chức tín dụng theo thỏa\r\nthuận.\n19. Chiết khấu là việc mua có kỳ hạn hoặc mua có bảo lưu quyền truy đòi các công cụ chuyển nhượng,\r\ngiấy tờ có giá khác của người thụ hưởng trước khi đến hạn thanh toán.\n20. Tái chiết khấu là việc chiết khấu\r\ncác công cụ chuyển nhượng, giấy tờ có giá khác đã được chiết khấu trước khi đến\r\nhạn thanh toán.\n21. Môi giới tiền tệ là việc làm trung\r\ngian có thu phí môi giới để thu xếp thực hiện các hoạt động ngân hàng và các hoạt\r\nđộng kinh doanh khác giữa các tổ chức tín dụng, tổ chức tài chính khác.\n22. Tài khoản\r\nthanh toán là tài khoản tiền gửi không kỳ hạn của khách hàng mở tại ngân\r\nhàng để sử dụng các dịch vụ thanh toán do ngân hàng cung ứng.\n23. Sản phẩm phái\r\nsinh là công cụ tài chính được định giá theo biến động dự kiến về giá trị của\r\nmột tài sản tài chính gốc như tỷ giá, lãi suất, ngoại hối, tiền tệ hoặc tài sản\r\ntài chính khác.\n24. Góp vốn, mua cổ phần của tổ chức tín dụng là việc tổ chức tín dụng góp vốn cấu thành vốn điều lệ, mua cổ phần của các\r\ndoanh nghiệp, tổ chức tín dụng khác, bao gồm cả việc cấp vốn, góp vốn vào công\r\nty con, công ty liên kết của tổ chức tín dụng; góp vốn vào quỹ đầu tư và ủy\r\nthác vốn cho các tổ chức khác góp vốn, mua cổ phần theo các hình thức nêu trên.\n25. Khoản đầu tư dưới hình thức góp vốn,\r\nmua cổ phần nhằm nắm quyền kiểm soát doanh nghiệp bao gồm khoản đầu tư chiếm\r\ntrên 50% vốn điều lệ hoặc vốn cổ phần có quyền biểu quyết của một doanh nghiệp\r\nhoặc khoản đầu tư khác đủ để chi phối quyết định của Đại hội đồng cổ đông hoặc\r\nHội đồng thành viên.\n26. Cổ đông lớn của tổ chức tín dụng cổ phần là cổ đông sở hữu trực tiếp, gián tiếp từ 5% vốn cổ phần có quyền biểu quyết trở\r\nlên của tổ chức tín dụng cổ phần đó.\n27. Sở hữu gián tiếp là việc tổ chức,\r\ncá nhân sở hữu vốn điều lệ, vốn cổ phần của tổ chức tín dụng thông qua người có\r\nliên quan hoặc thông qua ủy thác đầu tư.\n28 . Người có liên\r\nquan là tổ chức, cá nhân có quan hệ trực tiếp hoặc gián tiếp với tổ chức,\r\ncá nhân khác thuộc một trong các trường hợp sau đây:\na) Công ty mẹ với công ty con và ngược lại; tổ\r\nchức tín dụng với công ty con của tổ chức tín dụng và ngược lại; các công ty\r\ncon của cùng một công ty mẹ hoặc của cùng một tổ chức tín dụng với nhau; người\r\nquản lý, thành viên Ban kiểm soát của công ty mẹ hoặc của tổ chức tín dụng, cá\r\nnhân hoặc tổ chức có thẩm quyền bổ nhiệm những người này với công ty con và ngược\r\nlại;\nb) Công ty hoặc tổ chức tín dụng với người quản\r\nlý, thành viên Ban kiểm soát của công ty hoặc tổ chức tín dụng đó hoặc với công\r\nty, tổ chức có thẩm quyền bổ nhiệm những người đó và ngược lại;\nc) Công ty hoặc tổ chức tín dụng với tổ chức,\r\ncá nhân sở hữu từ 5% vốn điều lệ hoặc vốn cổ phần có quyền biểu quyết trở lên tại\r\ncông ty hoặc tổ chức tín dụng đó và ngược lại;\nd) Cá nhân với vợ, chồng, cha, mẹ, con, anh,\r\nchị, em của người này;\nđ) Công ty hoặc tổ chức tín dụng với cá nhân\r\ntheo quy định tại điểm d khoản này của người quản lý, thành viên Ban kiểm soát,\r\nthành viên góp vốn hoặc cổ đông sở hữu từ 5% vốn điều lệ hoặc vốn cổ phần có\r\nquyền biểu quyết trở lên của công ty hoặc tổ chức tín dụng đó và ngược lại;\ne) Cá nhân được ủy quyền đại diện cho tổ chức,\r\ncá nhân quy định tại các điểm a, b, c, d và đ khoản này với tổ chức, cá nhân ủy\r\nquyền; các cá nhân được ủy quyền đại diện phần vốn góp của cùng một tổ chức với\r\nnhau.\n29. Công ty liên kết\r\ncủa tổ chức tín dụng là công ty trong đó tổ chức tín dụng hoặc tổ chức tín\r\ndụng và người có liên quan của tổ chức tín dụng sở hữu trên 11% vốn điều lệ hoặc\r\ntrên 11% vốn cổ phần có quyền biểu quyết, nhưng không phải là công ty con của tổ\r\nchức tín dụng đó.\n30. Công ty con của\r\ntổ chức tín dụng là công ty thuộc một trong các trường hợp sau đây:\na) Tổ chức tín dụng hoặc tổ chức tín dụng và\r\nngười có liên quan của tổ chức tín dụng sở hữu trên 50% vốn điều lệ hoặc trên\r\n50% vốn cổ phần có quyền biểu quyết;\nb) Tổ chức tín dụng có quyền trực tiếp hoặc\r\ngián tiếp bổ nhiệm đa số hoặc tất cả thành viên Hội đồng quản trị, Hội đồng\r\nthành viên hoặc Tổng giám đốc (Giám đốc) của công ty con;\nc) Tổ chức tín dụng có quyền sửa đổi, bổ sung\r\nđiều lệ của công ty con;\nd) Tổ chức tín dụng và người có liên quan của\r\ntổ chức tín dụng trực tiếp hay gián tiếp kiểm soát việc thông qua nghị quyết,\r\nquyết định của Đại hội đồng cổ đông, Hội đồng quản trị, Hội đồng thành viên của\r\ncông ty con.\n31. Người quản lý tổ chức tín dụng bao\r\ngồm Chủ tịch, thành viên Hội đồng quản trị; Chủ tịch, thành viên Hội đồng thành\r\nviên; Tổng giám đốc (Giám đốc) và các chức danh quản lý khác theo quy định tại\r\nĐiều lệ của tổ chức tín dụng.\n32. Người điều\r\nhành tổ chức tín dụng bao gồm Tổng giám đốc (Giám đốc),\r\nPhó Tổng giám đốc (Phó giám đốc), Kế toán trưởng, Giám đốc chi nhánh và các chức\r\ndanh tương đương theo quy định tại Điều lệ của tổ chức tín dụng.'}, {'titles': ['LUẬT CÁC TỔ CHỨC\r\nTÍN DỤNG', 'Chương I NHỮNG\r\nQUY ĐỊNH CHUNG', 'Điều 5. Sử dụng thuật\r\nngữ liên quan đến hoạt động ngân hàng'], 'content': 'Tổ chức không phải là tổ chức tín dụng không\r\nđược phép sử dụng cụm từ hoặc thuật ngữ “tổ chức tín dụng”, “ngân hàng”, “công\r\nty tài chính”, “công ty cho thuê tài chính” hoặc các cụm từ, thuật ngữ khác\r\ntrong tên của tổ chức, chức danh hoặc trong các phần phụ thêm của tên, chức\r\ndanh hoặc trong giấy tờ giao dịch hoặc quảng cáo của mình nếu việc sử dụng cụm\r\ntừ, thuật ngữ đó có thể gây nhầm lẫn cho khách hàng về việc tổ chức của mình là\r\nmột tổ chức tín dụng.'}, {'titles': ['LUẬT CÁC TỔ CHỨC\r\nTÍN DỤNG', 'Chương I NHỮNG\r\nQUY ĐỊNH CHUNG', 'Điều 6. Hình thức tổ\r\nchức của tổ chức tín dụng'], 'content': '1. Ngân hàng thương mại trong nước được thành\r\nlập, tổ chức dưới hình thức công ty cổ phần, trừ trường hợp quy định tại khoản\r\n2 Điều này.\n2. Ngân hàng thương mại nhà nước được thành lập,\r\ntổ chức dưới hình thức công ty trách nhiệm hữu hạn một thành viên do Nhà nước sở\r\nhữu 100% vốn điều lệ.\n3. Tổ chức tín dụng phi ngân hàng trong nước\r\nđược thành lập, tổ chức dưới hình thức công ty cổ phần, công ty trách nhiệm hữu\r\nhạn.\n4. Tổ chức tín dụng liên doanh, tổ chức tín dụng\r\n100% vốn nước ngoài được thành lập, tổ chức dưới hình thức công ty trách nhiệm\r\nhữu hạn.\n5. Ngân hàng hợp tác xã, quỹ tín dụng nhân\r\ndân được thành lập, tổ chức dưới hình thức hợp tác xã.\n6. Tổ chức tài chính\r\nvi mô được thành lập, tổ chức dưới hình thức công ty trách nhiệm hữu hạn.'}, {'titles': ['LUẬT CÁC TỔ CHỨC\r\nTÍN DỤNG', 'Chương I NHỮNG\r\nQUY ĐỊNH CHUNG', 'Điều 7. Quyền tự chủ\r\nhoạt động'], 'content': '1. Tổ chức tín dụng, chi nhánh ngân hàng nước\r\nngoài có quyền tự chủ trong hoạt động kinh doanh và tự chịu trách nhiệm về kết\r\nquả kinh doanh của mình. Không tổ chức, cá nhân nào được can thiệp trái pháp luật\r\nvào hoạt động kinh doanh của tổ chức tín dụng, chi nhánh ngân hàng nước ngoài.\n2. Tổ chức tín dụng, chi nhánh ngân hàng nước\r\nngoài có quyền từ chối yêu cầu cấp tín dụng, cung ứng các dịch vụ khác nếu thấy\r\nkhông đủ điều kiện, không có hiệu quả, không phù hợp với quy định của pháp luật.'}, {'titles': ['LUẬT CÁC TỔ CHỨC\r\nTÍN DỤNG', 'Chương I NHỮNG\r\nQUY ĐỊNH CHUNG', 'Điều 8. Quyền hoạt động\r\nngân hàng'], 'content': '1. Tổ chức có đủ điều kiện theo quy định của\r\nLuật này và các quy định khác của pháp luật có liên quan được Ngân hàng Nhà nước\r\ncấp Giấy phép thì được thực hiện một hoặc một số hoạt động ngân hàng tại Việt\r\nNam.\n2. Nghiêm cấm cá\r\nnhân, tổ chức không phải là tổ chức tín dụng thực hiện hoạt động ngân hàng, trừ\r\ngiao dịch ký quỹ, giao dịch mua, bán lại chứng khoán của công ty chứng khoán.'}, {'titles': ['LUẬT CÁC TỔ CHỨC\r\nTÍN DỤNG', 'Chương I NHỮNG\r\nQUY ĐỊNH CHUNG', 'Điều 9. Hợp tác và cạnh\r\ntranh trong hoạt động ngân hàng'], 'content': '1. Tổ chức tín dụng, chi nhánh ngân hàng nước\r\nngoài được hợp tác và cạnh tranh trong hoạt động ngân hàng và hoạt động kinh\r\ndoanh khác theo quy định của pháp luật.\n2. Nghiêm cấm hành vi hạn chế cạnh tranh hoặc\r\nhành vi cạnh tranh không lành mạnh có nguy cơ gây tổn hại hoặc gây tổn hại đến\r\nviệc thực hiện chính sách tiền tệ quốc gia, an toàn của hệ thống các tổ chức\r\ntín dụng, lợi ích của Nhà nước, quyền và lợi ích hợp pháp của tổ chức, cá nhân.\n3. Chính phủ quy định cụ thể các hành vi cạnh\r\ntranh không lành mạnh trong hoạt động ngân hàng và hình thức xử lý các hành vi\r\nnày.'}, {'titles': ['LUẬT CÁC TỔ CHỨC\r\nTÍN DỤNG', 'Chương I NHỮNG\r\nQUY ĐỊNH CHUNG', 'Điều 10. Bảo vệ quyền\r\nlợi của khách hàng'], 'content': 'Tổ chức tín dụng, chi nhánh ngân hàng nước\r\nngoài có trách nhiệm sau đây:\n1. Tham gia tổ chức bảo toàn, bảo hiểm tiền gửi\r\ntheo quy định của pháp luật và công bố công khai việc tham gia tổ chức bảo\r\ntoàn, bảo hiểm tiền gửi tại trụ sở chính và chi nhánh;\n2. Tạo thuận lợi cho khách hàng gửi và rút tiền,\r\nbảo đảm thanh toán đủ, đúng hạn gốc và lãi của các khoản tiền gửi;\n3. Từ chối việc điều tra, phong tỏa, cầm giữ,\r\ntrích chuyển tiền gửi của khách hàng, trừ trường hợp có yêu cầu của cơ quan nhà\r\nnước có thẩm quyền theo quy định của pháp luật hoặc được sự chấp thuận của\r\nkhách hàng;\n4. Thông báo công khai lãi suất tiền gửi, phí\r\ndịch vụ, các quyền, nghĩa vụ của khách hàng đối với từng loại sản phẩm, dịch vụ\r\nđang cung ứng;\n5. Công bố thời gian giao dịch chính thức và\r\nkhông được tự ý ngừng giao dịch vào thời gian đã công bố. Trường hợp ngừng giao\r\ndịch trong thời gian giao dịch chính thức, tổ chức tín dụng, chi nhánh ngân\r\nhàng nước ngoài phải niêm yết tại nơi giao dịch chậm nhất là 24 giờ trước thời\r\nđiểm ngừng giao dịch. Tổ chức tín dụng, chi nhánh ngân hàng nước ngoài không được\r\nphép ngừng giao dịch quá 01 ngày làm việc, trừ trường hợp quy định tại điểm e khoản 1 Điều 29 của Luật này .'}, {'titles': ['LUẬT CÁC TỔ CHỨC\r\nTÍN DỤNG', 'Chương I NHỮNG\r\nQUY ĐỊNH CHUNG', 'Điều 11. Trách nhiệm\r\nphòng, chống rửa tiền, tài trợ khủng bố'], 'content': 'Tổ chức tín dụng, chi nhánh ngân hàng nước\r\nngoài có trách nhiệm sau đây:\n1. Không được che giấu, thực hiện hoạt động\r\nkinh doanh liên quan đến khoản tiền đã có bằng chứng về nguồn gốc bất hợp pháp;\n2. Xây dựng quy định nội bộ về phòng, chống rửa\r\ntiền, tài trợ khủng bố;\n3. Thực hiện các biện pháp phòng, chống rửa\r\ntiền, tài trợ khủng bố;\n4. Hợp tác với cơ quan nhà nước có thẩm quyền\r\ntrong việc điều tra hoạt động rửa tiền, tài trợ khủng bố.'}, {'titles': ['LUẬT CÁC TỔ CHỨC\r\nTÍN DỤNG', 'Chương I NHỮNG\r\nQUY ĐỊNH CHUNG', 'Điều 12. Người đại diện\r\ntheo pháp luật của tổ chức tín dụng'], 'content': '1. Người đại diện theo pháp luật của tổ chức\r\ntín dụng được quy định tại Điều lệ của tổ chức tín dụng và phải là một trong những\r\nngười sau đây:\na) Chủ tịch Hội đồng quản trị hoặc Chủ tịch Hội\r\nđồng thành viên của tổ chức tín dụng;\nb) Tổng giám đốc (Giám đốc) của tổ chức tín dụng.\n2. Người đại diện theo pháp luật của tổ chức\r\ntín dụng phải cư trú tại Việt Nam, trường hợp vắng mặt ở Việt Nam phải ủy quyền\r\nbằng văn bản cho người khác là người quản lý, người điều hành của tổ chức tín dụng\r\nđang cư trú tại Việt Nam để thực hiện quyền, nghĩa vụ của mình.'}, {'titles': ['LUẬ

In [6]:
df = df_raw.copy()
for i in range(len(df)):
    # if len(df["chunks"][i]) != 0:
    #     continue
    print(f"{i}/{len(df)}")
    chunks = chunk_document(df["content_html"][i].strip())
    df.at[i, "chunks"] = chunks
df[df['chunks'].apply(lambda x: len(x) == 0)]

0/2156
1/2156
2/2156
3/2156
4/2156
5/2156
6/2156
7/2156
8/2156
9/2156
10/2156
11/2156
12/2156
13/2156
14/2156
15/2156
16/2156
17/2156
18/2156
19/2156
20/2156
21/2156
22/2156
23/2156
24/2156
25/2156
26/2156
27/2156
28/2156
29/2156
30/2156
31/2156
32/2156
33/2156
34/2156
35/2156
36/2156
37/2156
38/2156
39/2156
40/2156
41/2156
42/2156
43/2156
44/2156
45/2156
46/2156
47/2156
48/2156
49/2156
50/2156
51/2156
52/2156
53/2156
54/2156
55/2156
56/2156
57/2156
58/2156
59/2156
60/2156
61/2156
62/2156
63/2156
64/2156
65/2156
66/2156
67/2156
68/2156
69/2156
70/2156
71/2156
72/2156
73/2156
74/2156
75/2156
76/2156
77/2156
78/2156
79/2156
80/2156
81/2156
82/2156
83/2156
84/2156
85/2156
86/2156
87/2156
88/2156
89/2156
90/2156
91/2156
92/2156
93/2156
94/2156
95/2156
96/2156
97/2156
98/2156
99/2156
100/2156
101/2156
102/2156
103/2156
104/2156
105/2156
106/2156
107/2156
108/2156
109/2156
110/2156
111/2156
112/2156
113/2156
114/2156
115/2156
116/2156
117/2156
118/2156
119/2156
120/2156
121/2156
122/2156
123/2156
124/2156
125/2156
126/2156
127/2156
128/2156
129/2156
130/2156
131/2156
132/2156
133/2156
134/2156
135/2156
136/2156
137/2156
138/2156
139/2156
140/2156
141/2156
142/2156
143/2156
144/2156
145/2156
146/2156
147/2156
148/2156
149/2156
150/2156
151/2156
152/2156
153/2156
154/2156
155/2156
156/2156
157/2156
158/2156
159/2156
160/2156
161/2156
162/2156
163/2156
164/2156
165/2156
166/2156
167/2156
168/2156
169/2156
170/2156
171/2156
172/2156
173/2156
174/2156
175/2156
176/2156
177/2156
178/2156
179/2156
180/2156
181/2156
182/2156
183/2156
184/2156
185/2156
186/2156
187/2156
188/2156
189/2156
190/2156
191/2156
192/2156
193/2156
194/2156
195/2156
196/2156
197/2156
198/2156
199/2156
200/2156
201/2156
202/2156
203/2156
204/2156
205/2156
206/2156
207/2156
208/2156
209/2156
210/2156
211/2156
212/2156
213/2156
214/2156
215/2156
216/2156
217/2156
218/2156
219/2156
220/2156
221/2156
222/2156
223/2156
224/2156
225/2156
226/2156
227/2156
228/2156
229/2156
230/2156
231/2156
232/2156
233/2156
234/2156
235/2156
236/2156
237/2156
238/2156
239/2156
240/2156
241/2156
242/2156
243/2156
244/2156
245/2156
246/2156
247/2156
248/2156
249/2156
250/2156
251/2156
252/2156
253/2156
254/2156
255/2156
256/2156
257/2156
258/2156
259/2156
260/2156
261/2156
262/2156
263/2156
264/2156
265/2156
266/2156
267/2156
268/2156
269/2156
270/2156
271/2156
272/2156
273/2156
274/2156
275/2156
276/2156
277/2156
278/2156
279/2156
280/2156
281/2156
282/2156
283/2156
284/2156
285/2156
286/2156
287/2156
288/2156
289/2156
290/2156
291/2156
292/2156
293/2156
294/2156
295/2156
296/2156
297/2156
298/2156
299/2156
300/2156
301/2156
302/2156
303/2156
304/2156
305/2156
306/2156
307/2156
308/2156
309/2156
310/2156
311/2156
312/2156
313/2156
314/2156
315/2156
316/2156
317/2156
318/2156
319/2156
320/2156
321/2156
322/2156
323/2156
324/2156
325/2156
326/2156
327/2156
328/2156
329/2156
330/2156
331/2156
332/2156
333/2156
334/2156
335/2156
336/2156
337/2156
338/2156
339/2156
340/2156
341/2156
342/2156
343/2156
344/2156
345/2156
346/2156
347/2156
348/2156
349/2156
350/2156
351/2156
352/2156
353/2156
354/2156
355/2156
356/2156
357/2156
358/2156
359/2156
360/2156
361/2156
362/2156
363/2156
364/2156
365/2156
366/2156
367/2156
368/2156
369/2156
370/2156
371/2156
372/2156
373/2156
374/2156
375/2156
376/2156
377/2156
378/2156
379/2156
380/2156
381/2156
382/2156
383/2156
384/2156
385/2156
386/2156
387/2156
388/2156
389/2156
390/2156
391/2156
392/2156
393/2156
394/2156
395/2156
396/2156
397/2156
398/2156
399/2156
400/2156
401/2156
402/2156
403/2156
404/2156
405/2156
406/2156
407/2156
408/2156
409/2156
410/2156
411/2156
412/2156
413/2156
414/2156
415/2156
416/2156
417/2156
418/2156
419/2156
420/2156
421/2156
422/2156
423/2156
424/2156
425/2156
426/2156
427/2156
428/2156
429/2156
430/2156
431/2156
432/2156
433/2156
434/2156
435/2156
436/2156
437/2156
438/2156
439/2156
440/2156
441/2156
442/2156
443/2156
444/2156
445/2156
446/2156
447/2156
448/2156
449/2156
450/2156
451/2156
452/2156
453/2156
454/2156
455/2156
456/2156
457/2156
458/2156
459/2156
460/2156
461/2156
462/2156
463/2156
464/2156
465/2156
466/2156
467/2156
468/2156
469/2156
470/2156
471/2156
472/2156
473/2156
474/2156
475/2156
476/2156
477/2156
478/2156
479/2156
480/2156
481/2156
482/2156
483/2156
484/2156
485/2156
486/2156
487/2156
488/2156
489/2156
490/2156
491/2156
492/2156
493/2156
494/2156
495/2156
496/2156
497/2156
498/2156
499/2156
500/2156
501/2156
502/2156
503/2156
504/2156
505/2156
506/2156
507/2156
508/2156
509/2156
510/2156
511/2156
512/2156
513/2156
514/2156
515/2156
516/2156
517/2156
518/2156
519/2156
520/2156
521/2156
522/2156
523/2156
524/2156
525/2156
526/2156
527/2156
528/2156
529/2156
530/2156
531/2156
532/2156
533/2156
534/2156
535/2156
536/2156
537/2156
538/2156
539/2156
540/2156
541/2156
542/2156
543/2156
544/2156
545/2156
546/2156
547/2156
548/2156
549/2156
550/2156
551/2156
552/2156
553/2156
554/2156
555/2156
556/2156
557/2156
558/2156
559/2156
560/2156
561/2156
562/2156
563/2156
564/2156
565/2156
566/2156
567/2156
568/2156
569/2156
570/2156
571/2156
572/2156
573/2156
574/2156
575/2156
576/2156
577/2156
578/2156
579/2156
580/2156
581/2156
582/2156
583/2156
584/2156
585/2156
586/2156
587/2156
588/2156
589/2156
590/2156
591/2156
592/2156
593/2156
594/2156
595/2156
596/2156
597/2156
598/2156
599/2156
600/2156
601/2156
602/2156
603/2156
604/2156
605/2156
606/2156
607/2156
608/2156
609/2156
610/2156
611/2156
612/2156
613/2156
614/2156
615/2156
616/2156
617/2156
618/2156
619/2156
620/2156
621/2156
622/2156
623/2156
624/2156
625/2156
626/2156
627/2156
628/2156
629/2156
630/2156
631/2156
632/2156
633/2156
634/2156
635/2156
636/2156
637/2156
638/2156
639/2156
640/2156
641/2156
642/2156
643/2156
644/2156
645/2156
646/2156
647/2156
648/2156
649/2156
650/2156
651/2156
652/2156
653/2156
654/2156
655/2156
656/2156
657/2156
658/2156
659/2156
660/2156
661/2156
662/2156
663/2156
664/2156
665/2156
666/2156
667/2156
668/2156
669/2156
670/2156
671/2156
672/2156
673/2156
674/2156
675/2156
676/2156
677/2156
678/2156
679/2156
680/2156
681/2156
682/2156
683/2156
684/2156
685/2156
686/2156
687/2156
688/2156
689/2156
690/2156
691/2156
692/2156
693/2156
694/2156
695/2156
696/2156
697/2156
698/2156
699/2156
700/2156
701/2156
702/2156
703/2156
704/2156
705/2156
706/2156
707/2156
708/2156
709/2156
710/2156
711/2156
712/2156
713/2156
714/2156
715/2156
716/2156
717/2156
718/2156
719/2156
720/2156
721/2156
722/2156
723/2156
724/2156
725/2156
726/2156
727/2156
728/2156
729/2156
730/2156
731/2156
732/2156
733/2156
734/2156
735/2156
736/2156
737/2156
738/2156
739/2156
740/2156
741/2156
742/2156
743/2156
744/2156
745/2156
746/2156
747/2156
748/2156
749/2156
750/2156
751/2156
752/2156
753/2156
754/2156
755/2156
756/2156
757/2156
758/2156
759/2156
760/2156
761/2156
762/2156
763/2156
764/2156
765/2156
766/2156
767/2156
768/2156
769/2156
770/2156
771/2156
772/2156
773/2156
774/2156
775/2156
776/2156
777/2156
778/2156
779/2156
780/2156
781/2156
782/2156
783/2156
784/2156
785/2156
786/2156
787/2156
788/2156
789/2156
790/2156
791/2156
792/2156
793/2156
794/2156
795/2156
796/2156
797/2156
798/2156
799/2156
800/2156
801/2156
802/2156
803/2156
804/2156
805/2156
806/2156
807/2156
808/2156
809/2156
810/2156
811/2156
812/2156
813/2156
814/2156
815/2156
816/2156
817/2156
818/2156
819/2156
820/2156
821/2156
822/2156
823/2156
824/2156
825/2156
826/2156
827/2156
828/2156
829/2156
830/2156
831/2156
832/2156
833/2156
834/2156
835/2156
836/2156
837/2156
838/2156
839/2156
840/2156
841/2156
842/2156
843/2156
844/2156
845/2156
846/2156
847/2156
848/2156
849/2156
850/2156
851/2156
852/2156
853/2156
854/2156
855/2156
856/2156
857/2156
858/2156
859/2156
860/2156
861/2156
862/2156
863/2156
864/2156
865/2156
866/2156
867/2156
868/2156
869/2156
870/2156
871/2156
872/2156
873/2156
874/2156
875/2156
876/2156
877/2156
878/2156
879/2156
880/2156
881/2156
882/2156
883/2156
884/2156
885/2156
886/2156
887/2156
888/2156
889/2156
890/2156
891/2156
892/2156
893/2156
894/2156
895/2156
896/2156
897/2156
898/2156
899/2156
900/2156
901/2156
902/2156
903/2156
904/2156
905/2156
906/2156
907/2156
908/2156
909/2156
910/2156
911/2156
912/2156
913/2156
914/2156
915/2156
916/2156
917/2156
918/2156
919/2156
920/2156
921/2156
922/2156
923/2156
924/2156
925/2156
926/2156
927/2156
928/2156
929/2156
930/2156
931/2156
932/2156
933/2156
934/2156
935/2156
936/2156
937/2156
938/2156
939/2156
940/2156
941/2156
942/2156
943/2156
944/2156
945/2156
946/2156
947/2156
948/2156
949/2156
950/2156
951/2156
952/2156
953/2156
954/2156
955/2156
956/2156
957/2156
958/2156
959/2156
960/2156
961/2156
962/2156
963/2156
964/2156
965/2156
966/2156
967/2156
968/2156
969/2156
970/2156
971/2156
972/2156
973/2156
974/2156
975/2156
976/2156
977/2156
978/2156
979/2156
980/2156
981/2156
982/2156
983/2156
984/2156
985/2156
986/2156
987/2156
988/2156
989/2156
990/2156
991/2156
992/2156
993/2156
994/2156
995/2156
996/2156
997/2156
998/2156
999/2156
1000/2156
1001/2156
1002/2156
1003/2156
1004/2156
1005/2156
1006/2156
1007/2156
1008/2156
1009/2156
1010/2156
1011/2156
1012/2156
1013/2156
1014/2156
1015/2156
1016/2156
1017/2156
1018/2156
1019/2156
1020/2156
1021/2156
1022/2156
1023/2156
1024/2156
1025/2156
1026/2156
1027/2156
1028/2156
1029/2156
1030/2156
1031/2156
1032/2156
1033/2156
1034/2156
1035/2156
1036/2156
1037/2156
1038/2156
1039/2156
1040/2156
1041/2156
1042/2156
1043/2156
1044/2156
1045/2156
1046/2156
1047/2156
1048/2156
1049/2156
1050/2156
1051/2156
1052/2156
1053/2156
1054/2156
1055/2156
1056/2156
1057/2156
1058/2156
1059/2156
1060/2156
1061/2156
1062/2156
1063/2156
1064/2156
1065/2156
1066/2156
1067/2156
1068/2156
1069/2156
1070/2156
1071/2156
1072/2156
1073/2156
1074/2156
1075/2156
1076/2156
1077/2156
1078/2156
1079/2156
1080/2156
1081/2156
1082/2156
1083/2156
1084/2156
1085/2156
1086/2156
1087/2156
1088/2156
1089/2156
1090/2156
1091/2156
1092/2156
1093/2156
1094/2156
1095/2156
1096/2156
1097/2156
1098/2156
1099/2156
1100/2156
1101/2156
1102/2156
1103/2156
1104/2156
1105/2156
1106/2156
1107/2156
1108/2156
1109/2156
1110/2156
1111/2156
1112/2156
1113/2156
1114/2156
1115/2156
1116/2156
1117/2156
1118/2156
1119/2156
1120/2156
1121/2156
1122/2156
1123/2156
1124/2156
1125/2156
1126/2156
1127/2156
1128/2156
1129/2156
1130/2156
1131/2156
1132/2156
1133/2156
1134/2156
1135/2156
1136/2156
1137/2156
1138/2156
1139/2156
1140/2156
1141/2156
1142/2156
1143/2156
1144/2156
1145/2156
1146/2156
1147/2156
1148/2156
1149/2156
1150/2156
1151/2156
1152/2156
1153/2156
1154/2156
1155/2156
1156/2156
1157/2156
1158/2156
1159/2156
1160/2156
1161/2156
1162/2156
1163/2156
1164/2156
1165/2156
1166/2156
1167/2156
1168/2156
1169/2156
1170/2156
1171/2156
1172/2156
1173/2156
1174/2156
1175/2156
1176/2156
1177/2156
1178/2156
1179/2156
1180/2156
1181/2156
1182/2156
1183/2156
1184/2156
1185/2156
1186/2156
1187/2156
1188/2156
1189/2156
1190/2156
1191/2156
1192/2156
1193/2156
1194/2156
1195/2156
1196/2156
1197/2156
1198/2156
1199/2156
1200/2156
1201/2156
1202/2156
1203/2156
1204/2156
1205/2156
1206/2156
1207/2156
1208/2156
1209/2156
1210/2156
1211/2156
1212/2156
1213/2156
1214/2156
1215/2156
1216/2156
1217/2156
1218/2156
1219/2156
1220/2156
1221/2156
1222/2156
1223/2156
1224/2156
1225/2156
1226/2156
1227/2156
1228/2156
1229/2156
1230/2156
1231/2156
1232/2156
1233/2156
1234/2156
1235/2156
1236/2156
1237/2156
1238/2156
1239/2156
1240/2156
1241/2156
1242/2156
1243/2156
1244/2156
1245/2156
1246/2156
1247/2156
1248/2156
1249/2156
1250/2156
1251/2156
1252/2156
1253/2156
1254/2156
1255/2156
1256/2156
1257/2156
1258/2156
1259/2156
1260/2156
1261/2156
1262/2156
1263/2156
1264/2156
1265/2156
1266/2156
1267/2156
1268/2156
1269/2156
1270/2156
1271/2156
1272/2156
1273/2156
1274/2156
1275/2156
1276/2156
1277/2156
1278/2156
1279/2156
1280/2156
1281/2156
1282/2156
1283/2156
1284/2156
1285/2156
1286/2156
1287/2156
1288/2156
1289/2156
1290/2156
1291/2156
1292/2156
1293/2156
1294/2156
1295/2156
1296/2156
1297/2156
1298/2156
1299/2156
1300/2156
1301/2156
1302/2156
1303/2156
1304/2156
1305/2156
1306/2156
1307/2156
1308/2156
1309/2156
1310/2156
1311/2156
1312/2156
1313/2156
1314/2156
1315/2156
1316/2156
1317/2156
1318/2156
1319/2156
1320/2156
1321/2156
1322/2156
1323/2156
1324/2156
1325/2156
1326/2156
1327/2156
1328/2156
1329/2156
1330/2156
1331/2156
1332/2156
1333/2156
1334/2156
1335/2156
1336/2156
1337/2156
1338/2156
1339/2156
1340/2156
1341/2156
1342/2156
1343/2156
1344/2156
1345/2156
1346/2156
1347/2156
1348/2156
1349/2156
1350/2156
1351/2156
1352/2156
1353/2156
1354/2156
1355/2156
1356/2156
1357/2156
1358/2156
1359/2156
1360/2156
1361/2156
1362/2156
1363/2156
1364/2156
1365/2156
1366/2156
1367/2156
1368/2156
1369/2156
1370/2156
1371/2156
1372/2156
1373/2156
1374/2156
1375/2156
1376/2156
1377/2156
1378/2156
1379/2156
1380/2156
1381/2156
1382/2156
1383/2156
1384/2156
1385/2156
1386/2156
1387/2156
1388/2156
1389/2156
1390/2156
1391/2156
1392/2156
1393/2156
1394/2156
1395/2156
1396/2156
1397/2156
1398/2156
1399/2156
1400/2156
1401/2156
1402/2156
1403/2156
1404/2156
1405/2156
1406/2156
1407/2156
1408/2156
1409/2156
1410/2156
1411/2156
1412/2156
1413/2156
1414/2156
1415/2156
1416/2156
1417/2156
1418/2156
1419/2156
1420/2156
1421/2156
1422/2156
1423/2156
1424/2156
1425/2156
1426/2156
1427/2156
1428/2156
1429/2156
1430/2156
1431/2156
1432/2156
1433/2156
1434/2156
1435/2156
1436/2156
1437/2156
1438/2156
1439/2156
1440/2156
1441/2156
1442/2156
1443/2156
1444/2156
1445/2156
1446/2156
1447/2156
1448/2156
1449/2156
1450/2156
1451/2156
1452/2156
1453/2156
1454/2156
1455/2156
1456/2156
1457/2156
1458/2156
1459/2156
1460/2156
1461/2156
1462/2156
1463/2156
1464/2156
1465/2156
1466/2156
1467/2156
1468/2156
1469/2156
1470/2156
1471/2156
1472/2156
1473/2156
1474/2156
1475/2156
1476/2156
1477/2156
1478/2156
1479/2156
1480/2156
1481/2156
1482/2156
1483/2156
1484/2156
1485/2156
1486/2156
1487/2156
1488/2156
1489/2156
1490/2156
1491/2156
1492/2156
1493/2156
1494/2156
1495/2156
1496/2156
1497/2156
1498/2156
1499/2156
1500/2156
1501/2156
1502/2156
1503/2156
1504/2156
1505/2156
1506/2156
1507/2156
1508/2156
1509/2156
1510/2156
1511/2156
1512/2156
1513/2156
1514/2156
1515/2156
1516/2156
1517/2156
1518/2156
1519/2156
1520/2156
1521/2156
1522/2156
1523/2156
1524/2156
1525/2156
1526/2156
1527/2156
1528/2156
1529/2156
1530/2156
1531/2156
1532/2156
1533/2156
1534/2156
1535/2156
1536/2156
1537/2156
1538/2156
1539/2156
1540/2156
1541/2156
1542/2156
1543/2156
1544/2156
1545/2156
1546/2156
1547/2156
1548/2156
1549/2156
1550/2156
1551/2156
1552/2156
1553/2156
1554/2156
1555/2156
1556/2156
1557/2156
1558/2156
1559/2156
1560/2156
1561/2156
1562/2156
1563/2156
1564/2156
1565/2156
1566/2156
1567/2156
1568/2156
1569/2156
1570/2156
1571/2156
1572/2156
1573/2156
1574/2156
1575/2156
1576/2156
1577/2156
1578/2156
1579/2156
1580/2156
1581/2156
1582/2156
1583/2156
1584/2156
1585/2156
1586/2156
1587/2156
1588/2156
1589/2156
1590/2156
1591/2156
1592/2156
1593/2156
1594/2156
1595/2156
1596/2156
1597/2156
1598/2156
1599/2156
1600/2156
1601/2156
1602/2156
1603/2156
1604/2156
1605/2156
1606/2156
1607/2156
1608/2156
1609/2156
1610/2156
1611/2156
1612/2156
1613/2156
1614/2156
1615/2156
1616/2156
1617/2156
1618/2156
1619/2156
1620/2156
1621/2156
1622/2156
1623/2156
1624/2156
1625/2156
1626/2156
1627/2156
1628/2156
1629/2156
1630/2156
1631/2156
1632/2156
1633/2156
1634/2156
1635/2156
1636/2156
1637/2156
1638/2156
1639/2156
1640/2156
1641/2156
1642/2156
1643/2156
1644/2156
1645/2156
1646/2156
1647/2156
1648/2156
1649/2156
1650/2156
1651/2156
1652/2156
1653/2156
1654/2156
1655/2156
1656/2156
1657/2156
1658/2156
1659/2156
1660/2156
1661/2156
1662/2156
1663/2156
1664/2156
1665/2156
1666/2156
1667/2156
1668/2156
1669/2156
1670/2156
1671/2156
1672/2156
1673/2156
1674/2156
1675/2156
1676/2156
1677/2156
1678/2156
1679/2156
1680/2156
1681/2156
1682/2156
1683/2156
1684/2156
1685/2156
1686/2156
1687/2156
1688/2156
1689/2156
1690/2156
1691/2156
1692/2156
1693/2156
1694/2156
1695/2156
1696/2156
1697/2156
1698/2156
1699/2156
1700/2156
1701/2156
1702/2156
1703/2156
1704/2156
1705/2156
1706/2156
1707/2156
1708/2156
1709/2156
1710/2156
1711/2156
1712/2156
1713/2156
1714/2156
1715/2156
1716/2156
1717/2156
1718/2156
1719/2156
1720/2156
1721/2156
1722/2156
1723/2156
1724/2156
1725/2156
1726/2156
1727/2156
1728/2156
1729/2156
1730/2156
1731/2156
1732/2156
1733/2156
1734/2156
1735/2156
1736/2156
1737/2156
1738/2156
1739/2156
1740/2156
1741/2156
1742/2156
1743/2156
1744/2156
1745/2156
1746/2156
1747/2156
1748/2156
1749/2156
1750/2156
1751/2156
1752/2156
1753/2156
1754/2156
1755/2156
1756/2156
1757/2156
1758/2156
1759/2156
1760/2156
1761/2156
1762/2156
1763/2156
1764/2156
1765/2156
1766/2156
1767/2156
1768/2156
1769/2156
1770/2156
1771/2156
1772/2156
1773/2156
1774/2156
1775/2156
1776/2156
1777/2156
1778/2156
1779/2156
1780/2156
1781/2156
1782/2156
1783/2156
1784/2156
1785/2156
1786/2156
1787/2156
1788/2156
1789/2156
1790/2156
1791/2156
1792/2156
1793/2156
1794/2156
1795/2156
1796/2156
1797/2156
1798/2156
1799/2156
1800/2156
1801/2156
1802/2156
1803/2156
1804/2156
1805/2156
1806/2156
1807/2156
1808/2156
1809/2156
1810/2156
1811/2156
1812/2156
1813/2156
1814/2156
1815/2156
1816/2156
1817/2156
1818/2156
1819/2156
1820/2156
1821/2156
1822/2156
1823/2156
1824/2156
1825/2156
1826/2156
1827/2156
1828/2156
1829/2156
1830/2156
1831/2156
1832/2156
1833/2156
1834/2156
1835/2156
1836/2156
1837/2156
1838/2156
1839/2156
1840/2156
1841/2156
1842/2156
1843/2156
1844/2156
1845/2156
1846/2156
1847/2156
1848/2156
1849/2156
1850/2156
1851/2156
1852/2156
1853/2156
1854/2156
1855/2156
1856/2156
1857/2156
1858/2156
1859/2156
1860/2156
1861/2156
1862/2156
1863/2156
1864/2156
1865/2156
1866/2156
1867/2156
1868/2156
1869/2156
1870/2156
1871/2156
1872/2156
1873/2156
1874/2156
1875/2156
1876/2156
1877/2156
1878/2156
1879/2156
1880/2156
1881/2156
1882/2156
1883/2156
1884/2156
1885/2156
1886/2156
1887/2156
1888/2156
1889/2156
1890/2156
1891/2156
1892/2156
1893/2156
1894/2156
1895/2156
1896/2156
1897/2156
1898/2156
1899/2156
1900/2156
1901/2156
1902/2156
1903/2156
1904/2156
1905/2156
1906/2156
1907/2156
1908/2156
1909/2156
1910/2156
1911/2156
1912/2156
1913/2156
1914/2156
1915/2156
1916/2156
1917/2156
1918/2156
1919/2156
1920/2156
1921/2156
1922/2156
1923/2156
1924/2156
1925/2156
1926/2156
1927/2156
1928/2156
1929/2156
1930/2156
1931/2156
1932/2156
1933/2156
1934/2156
1935/2156
1936/2156
1937/2156
1938/2156
1939/2156
1940/2156
1941/2156
1942/2156
1943/2156
1944/2156
1945/2156
1946/2156
1947/2156
1948/2156
1949/2156
1950/2156
1951/2156
1952/2156
1953/2156
1954/2156
1955/2156
1956/2156
1957/2156
1958/2156
1959/2156
1960/2156
1961/2156
1962/2156
1963/2156
1964/2156
1965/2156
1966/2156
1967/2156
1968/2156
1969/2156
1970/2156
1971/2156
1972/2156
1973/2156
1974/2156
1975/2156
1976/2156
1977/2156
1978/2156
1979/2156
1980/2156
1981/2156
1982/2156
1983/2156
1984/2156
1985/2156
1986/2156
1987/2156
1988/2156
1989/2156
1990/2156
1991/2156
1992/2156
1993/2156
1994/2156
1995/2156
1996/2156
1997/2156
1998/2156
1999/2156
2000/2156
2001/2156
2002/2156
2003/2156
2004/2156
2005/2156
2006/2156
2007/2156
2008/2156
2009/2156
2010/2156
2011/2156
2012/2156
2013/2156
2014/2156
2015/2156
2016/2156
2017/2156
2018/2156
2019/2156
2020/2156
2021/2156
2022/2156
2023/2156
2024/2156
2025/2156
2026/2156
2027/2156
2028/2156
2029/2156
2030/2156
2031/2156
2032/2156
2033/2156
2034/2156
2035/2156
2036/2156
2037/2156
2038/2156
2039/2156
2040/2156
2041/2156
2042/2156
2043/2156
2044/2156
2045/2156
2046/2156
2047/2156
2048/2156
2049/2156
2050/2156
2051/2156
2052/2156
2053/2156
2054/2156
2055/2156
2056/2156
2057/2156
2058/2156
2059/2156
2060/2156
2061/2156
2062/2156
2063/2156
2064/2156
2065/2156
2066/2156
2067/2156
2068/2156
2069/2156
2070/2156
2071/2156
2072/2156
2073/2156
2074/2156
2075/2156
2076/2156
2077/2156
2078/2156
2079/2156
2080/2156
2081/2156
2082/2156
2083/2156
2084/2156
2085/2156
2086/2156
2087/2156
2088/2156
2089/2156
2090/2156
2091/2156
2092/2156
2093/2156
2094/2156
2095/2156
2096/2156
2097/2156
2098/2156
2099/2156
2100/2156
2101/2156
2102/2156
2103/2156
2104/2156
2105/2156
2106/2156
2107/2156
2108/2156
2109/2156
2110/2156

,law_id,url,content_html,chunks,error
83,02/2020/TT-NHNN,https://thuvienphapluat.vn/van-ban/Thuong-mai/...,"\r\n<!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 4....",[],None
104,130/2003/QĐ-TTg,https://thuvienphapluat.vn/van-ban/Tien-te-Nga...,"\r\n<!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 4....",[],None
507,03/2013/TTLT-TANDTC-VKSNDTC,https://thuvienphapluat.vn/van-ban/Thu-tuc-To-...,"\r\n<!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 4....",[],None
521,590/QĐ-VKSTC-V3,https://thuvienphapluat.vn/van-ban/Thu-tuc-To-...,"\r\n<!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 4....",[],None
523,386/2016/QĐ-TANDTC,https://thuvienphapluat.vn/van-ban/Thu-tuc-To-...,"\r\n<!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 4....",[],None
714,46/2020/TT-BGDĐT,https://thuvienphapluat.vn/van-ban/Giao-duc/Th...,"\r\n<!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 4....",[],None
842,1919/QĐ-BTC,https://thuvienphapluat.vn/van-ban/Xuat-nhap-k...,"\r\n<!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 4....",[],None
860,188/QĐ-TCHQ,https://thuvienphapluat.vn/van-ban/Xuat-nhap-k...,"\r\n<!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 4....",[],None
1069,70/2018/QH14,https://thuvienphapluat.vn/van-ban/Tai-chinh-n...,"\r\n<!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 4....",[],None
1379,963/QĐ-BCT,https://thuvienphapluat.vn/van-ban/Thuong-mai/...,"\r\n<!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 4....",[],None
1464,742/QĐ-BHXH,https://thuvienphapluat.vn/van-ban/Ke-toan-Kie...,"\r\n<!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 4....",[],None
1605,53/2012/TT-BGTVT,https://thuvienphapluat.vn/van-ban/Thuong-mai/...,"\r\n<!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 4....",[],None
1738,78-QĐ/TW,https://thuvienphapluat.vn/van-ban/Bo-may-hanh...,"\r\n<!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 4....",[],None
1748,166-QĐ/TW,https://thuvienphapluat.vn/van-ban/Bo-may-hanh...,"\r\n<!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 4....",[],None
1756,230/QĐ-UBDT,https://thuvienphapluat.vn/van-ban/Bo-may-hanh...,"\r\n<!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 4....",[],None
1843,2196/QĐ-BGTVT,https://thuvienphapluat.vn/van-ban/Xay-dung-Do...,"\r\n<!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 4....",[],Just a moment...
1884,32/2018/QĐ-TTg,https://thuvienphapluat.vn/van-ban/Bo-may-hanh...,"\r\n<!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 4....",[],None
1908,266/QĐ-BTP,https://thuvienphapluat.vn/van-ban/Bo-may-hanh...,"\r\n<!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 4....",[],None
2125,1332/QĐ-BGTVT,https://luatvietnam.vn/co-cau-to-chuc/quyet-di...,"<!DOCTYPE html><html lang=""vi""><head><meta cha...",[],Just a moment...
2129,06/2012/TT-BNV,https://thuvienphapluat.vn/van-ban/Bo-may-hanh...,"\r\n<!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 4....",[],None

In [7]:
df.to_parquet("../data/law_content_chunks.parquet",
    index=False,
    compression="zstd",
    engine="pyarrow"
)