In [1]:
import json

import pandas as pd

df_chunks = pd.read_parquet("data/law_content_chunks.parquet", engine="pyarrow")

df_chunks.head(3)

,law_id,url,content_html,chunks,error
0,14/2022/TT-NHNN,https://thuvienphapluat.vn/van-ban/Tien-te-Nga...,"\r\n<!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 4....",[{'content': 'NGÂN HÀNG NHÀ NƯỚC VIỆT NAM -...,None
1,11/2022/TT-NHNN,https://thuvienphapluat.vn/van-ban/Tien-te-Nga...,"\r\n<!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 4....",[{'content': 'NGÂN HÀNG NHÀ NƯỚC VIỆT NAM -...,None
2,02/2007/TT-BNV,https://thuvienphapluat.vn/van-ban/Lao-dong-Ti...,"\r\n<!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 4....",[{'content': 'BỘ NỘI VỤ ****** CỘNG HOÀ ...,None

In [3]:
df = pd.read_parquet("data/train/legal_corpus.parquet", engine="pyarrow")
df.head(3)

   id           law_id  aid                                    content_Article
0   0  14/2022/TT-NHNN    0  1. Thông tư này quy định mã số, tiêu chuẩn chu...
1   0  14/2022/TT-NHNN    1  1. Kiểm soát viên cao cấp ngân hàng Mã số: 07....
2   0  14/2022/TT-NHNN    2  1. Có bản lĩnh chính trị vững vàng, kiên định ...

In [25]:
from src.preprocess.text_utils import normalize_text

id = 574
law_id = df[df["aid"]==id].reset_index(drop=True)["law_id"][0]
df_temp = df_chunks[df_chunks["law_id"]==law_id].reset_index(drop=True)
url = df_temp["url"][0]
chunks = df_temp["chunks"][0]
content_html = df_temp["content_html"][0]
print("aid:", id)
print("law_id:", law_id)
print("law url:", url)
print("-"*50)
print("Nội dung của aid:\n", df["content_Article"][id])
print("-"*50)
print("Nội dung của chunks trích xuất được từ HTML:\n", chunks)
# print("-"*50)
# print(content_html)

aid: 574
law_id: 38/2015/TT-NHNN
law url: https://thuvienphapluat.vn/van-ban/Thuong-mai/Thong-tu-38-2015-TT-NHNN-sua-doi-Thong-tu-16-2012-TT-NHNN-huong-dan-hoat-dong-kinh-doanh-vang-300421.aspx
--------------------------------------------------
Nội dung của aid:
 Bãi bỏ khoản 1 Điều 4 Thông tư 16/2012/TT-NHNN .
--------------------------------------------------
Nội dung của chunks trích xuất được từ HTML:
 [{'content': 'NGÂN HÀNG NHÀ\r\n  NƯỚC VIỆT NAM ------- CỘNG HÒA XÃ HỘI\r\n  CHỦ NGHĨA VIỆT NAM Độc lập - Tự do - Hạnh phúc --------------- Số:\r\n  38/2015/TT-NHNN Hà Nội, ngày 31 tháng 12 năm 2015', 'titles': array([], dtype=object)}
 {'content': 'Căn cứ Luật Ngân\r\nhàng Nhà nước Việt Nam số 46/2010/QH12 ngày 16 tháng 6 năm 2010;\nCăn cứ Luật các tổ\r\nchức tín dụng số 47/2010/QH12 ngày 16 tháng 6 năm 2010;\nCăn cứ Nghị định số 156/2013/NĐ-CP ngày 11 tháng 11 năm 2013 của Chính phủ quy định chức năng, nhiệm vụ, quyền hạn\r\nvà cơ cấu tổ chức của Ngân hàng Nhà nước Việt Nam;\nCăn cứ Nghị định số 24/2012/NĐ-CP ngày 03 tháng 4 năm 2012 của Chính phủ về quản lý hoạt động kinh doanh vàng;\nTheo đề nghị của Vụ trưởng Vụ Quản lý ngoại hối;\nThống đốc Ngân hàng Nhà nước Việt Nam ban hành\r\nThông tư sửa đổi, bổ sung một số điều của Thông tư số 16/2012/TT-NHNN ngày 25 tháng 5 năm 2012 của Thống\r\nđốc Ngân hàng Nhà nước Việt Nam hướng dẫn một số điều của Nghị định 24/2012/NĐ-CP ngày 03 tháng 4 năm 2012 của\r\nChính phủ về quản lý hoạt động kinh doanh vàng (sau đây gọi là Thông tư 16/2012/TT-NHNN ).', 'titles': array(['THÔNG TƯ SỬA\r\nĐỔI, BỔ SUNG MỘT SỐ ĐIỀU CỦA THÔNG TƯ SỐ16/2012/TT-NHNNNGÀY 25 THÁNG 5 NĂM\r\n2012 CỦA THỐNG ĐỐC NGÂN HÀNG NHÀ NƯỚC VIỆT NAM HƯỚNG DẪN MỘT SỐ ĐIỀU CỦA NGHỊ ĐỊNH24/2012/NĐ-CPNGÀY 03 THÁNG 4 NĂM 2012 CỦA CHÍNH PHỦ VỀ QUẢN LÝ HOẠT ĐỘNG KINH\r\nDOANH VÀNG'],
       dtype=object)}

In [15]:
from src.preprocess.text_utils import is_text_similar, normalize_titles
count_miss_title = 0
df["titles"] = None

for i in range(len(df)):
    law_id = df["law_id"][i]
    df_temp = df_chunks[df_chunks["law_id"] == law_id].reset_index(drop=True)
    if len(df_temp)==0 or len(df_temp)>1:
        print(f'Không tìm thấy law_id: {law_id}')
        continue
    chunks = df_temp["chunks"][0]
    if len(chunks)==0:
        print(f'Không có chunks trong law_id: {law_id}')
        continue
    content = df["content_Article"][i]
    is_matched = False
    for chunk in chunks:
        if is_text_similar(content, chunk["content"]):
            df.at[i, "titles"] = normalize_titles(chunk["titles"])
            is_matched = True
            break

    if not is_matched:
        print(df["aid"][i])
        if len(chunks) > 1:
            df.at[i, "titles"] = normalize_titles(chunks[1]["titles"][0:1])
        else:
            df.at[i, "titles"] = []
        count_miss_title += 1
        # break

441
574
763
780
781
783
784
811
1050
1125
1127
1128
1134
1135
1175
1176
1177
1178
1179
1180
1181
1182
1183
1184
1185
1186
1187
1188
1189
1190
1191
1192
1193
1194
1195
1196
1197
1198
1199
1200
1201
1202
1203
1204
1205
1206
1207
1208
1209
1210
1211
1212
1213
1214
1215
1216
1217
1218
1219
1220
1221
1222
1223
1224
1225
1226
1227
1230
1353
1355
1357
1506
Không có chunks trong law_id: 02/2020/TT-NHNN
Không có chunks trong law_id: 02/2020/TT-NHNN
Không có chunks trong law_id: 02/2020/TT-NHNN
Không có chunks trong law_id: 02/2020/TT-NHNN
Không có chunks trong law_id: 02/2020/TT-NHNN
Không có chunks trong law_id: 02/2020/TT-NHNN
Không có chunks trong law_id: 02/2020/TT-NHNN
2364
Không có chunks trong law_id: 130/2003/QĐ-TTg
Không có chunks trong law_id: 130/2003/QĐ-TTg
Không có chunks trong law_id: 130/2003/QĐ-TTg
Không có chunks trong law_id: 130/2003/QĐ-TTg
Không có chunks trong law_id: 130/2003/QĐ-TTg
Không có chunks trong law_id: 130/2003/QĐ-TTg
Không có chunks trong law_id: 130/2003/QĐ-TTg
Không có chunks trong law_id: 130/2003/QĐ-TTg
Không có chunks trong law_id: 130/2003/QĐ-TTg
Không có chunks trong law_id: 130/2003/QĐ-TTg
2711
2956
3407
3525
3526
3527
3528
3529
3530
3531
3532
3533
3534
3535
3536
3537
3538
3539
3540
3541
3542
3543
3544
3545
3546
3547
3548
3549
3550
3551
3552
3553
3554
3555
3556
3557
3558
3559
3560
3561
3562
3563
3564
3565
3566
3567
3568
3569
3570
3571
3572
3573
3574
3575
3576
4183
4185
4729
4897
4898
4899
5794
5795
5797
5798
5799
5800
5801
5802
5803
5804
5805
5806
5807
5808
5809
5810
5811
5812
5813
5814
5815
5816
5817
5818
5819
5820
5821
5822
5823
5824
5825
5826
5827
5828
5829
5830
5831
5832
5833
5834
5835
5836
5837
5838
5839
5840
5841
5842
5843
5844
5845
5846
5847
5848
5849
5850
5851
5852
5853
5854
5855
5856
5857
5858
5859
5860
5861
5862
5863
5864
6161
6162
6163
6164
6165
6167
6168
6169
6171
6391
6569
6570
7089
7090
7091
7092
7093
7754
8242
8243
8244
8393
8404
8405
8406
8407
8408
8409
8410
8411
8412
8413
8414
8415
8416
8417
8418
8853
9147
9282
9450
9451
9493
9494
9495
9708
9711
9712
9713
9714
9715
9716
9741
9742
9743
9744
9745
9746
9747
9748
9749
9750
9751
9752
9753
9754
9755
9756
9757
9926
9927
10406
10411
10446
10537
10817
10818
10819
10820
10821
10822
10823
10824
10858
10861
11230
11231
11232
11233
11234
11235
11236
11237
11238
11239
11240
11241
11242
11243
11244
12140
12212
12747
12752
12753
12754
12771
12772
12773
12774
12775
12776
12777
12778
12779
12780
12781
12782
12783
13066
13067
13068
13266
13267
13268
13272
13274
13283
13286
13378
13379
13385
13399
14286
14287
14306
14307
14308
14309
14310
14311
14312
14313
14314
14315
14316
14317
14318
14319
14320
14321
14322
14323
14324
14325
14326
14327
14328
14329
14330
14331
14332
14333
14334
14335
14336
14337
14338
14339
14340
14341
14342
14343
14344
14345
14346
14347
14348
14349
14350
14351
14352
14353
14354
14355
14356
14357
14358
14359
14360
14361
14362
14363
14364
14365
14366
14367
14368
14369
14370
14371
14372
14373
14374
14375
14376
14377
14378
14379
14380
14381
14382
14383
14384
14385
14386
14387
14388
14389
14390
14391
14392
14393
14394
14395
14396
14397
14398
14399
14400
14401
14402
14403
14404
14405
14406
14407
14408
14409
14410
14411
14412
14413
14414
14415
14416
14417
14418
14419
14420
14421
14422
14423
14424
14425
14426
14427
14428
14429
14430
14431
14432
14433
14434
14435
14436
14437
14438
14439
14440
14441
14442
14443
14444
14445
14446
14447
14448
14449
14450
14451
14452
14453
14454
14455
14456
14457
14458
14459
14460
14461
14462
14463
14464
14465
14466
14467
14468
14469
14470
14471
14472
14473
14474
14475
14476
14477
14478
14479
14480
14481
14482
14483
14484
14485
14486
14487
14488
14489
14490
14491
14492
14493
14494
14495
14496
14497
14498
14499
14500
14501
14502
14503
14504
14505
14506
14507
14508
14509
14510
14511
14512
14513
14514
14515
14516
14517
14518
14519
14520
14521
14522
14523
14524
14525
14526
14527
14528
14529
14530
14531
14532
14533
14534
14535
14536
14537
14538
14539
14540
14541
14542
14543
14544
14545
14546
14547
14548
14549
14550
14551
14552
14553
14554
14555
14556
14557
14558
14559
14560
14561
14562
14563
14564
14565
14566
14567
14568
14569
14570
14571
14572
14573
14574
14575
14576
14577
14578
14579
14580
14581
14582
14583
14584
14585
14586
14587
14588
14589
14590
14591
14592
14593
14594
14595
14596
14597
14598
14599
14600
14601
14602
14603
14604
14605
14606
14607
14608
14609
14610
14611
14612
14613
14614
14615
14616
14617
14618
14619
14620
14621
14622
14623
14624
14625
14626
14627
14628
14629
14630
14631
14632
14633
14634
14635
14636
14637
14638
14639
14640
14641
14642
14643
14644
14645
14646
14647
14648
14649
14650
14651
14652
14653
14654
14655
14656
14657
14658
14659
14660
14661
14662
14663
14664
14665
14666
14667
14668
14669
14670
14671
14672
14673
14674
14675
14676
14677
Không có chunks trong law_id: 03/2013/TTLT-TANDTC-VKSNDTC
Không có chunks trong law_id: 03/2013/TTLT-TANDTC-VKSNDTC
Không có chunks trong law_id: 03/2013/TTLT-TANDTC-VKSNDTC
Không có chunks trong law_id: 03/2013/TTLT-TANDTC-VKSNDTC
Không có chunks trong law_id: 03/2013/TTLT-TANDTC-VKSNDTC
Không có chunks trong law_id: 03/2013/TTLT-TANDTC-VKSNDTC
Không có chunks trong law_id: 03/2013/TTLT-TANDTC-VKSNDTC
Không có chunks trong law_id: 03/2013/TTLT-TANDTC-VKSNDTC
Không có chunks trong law_id: 03/2013/TTLT-TANDTC-VKSNDTC
Không có chunks trong law_id: 03/2013/TTLT-TANDTC-VKSNDTC
Không có chunks trong law_id: 03/2013/TTLT-TANDTC-VKSNDTC
Không có chunks trong law_id: 03/2013/TTLT-TANDTC-VKSNDTC
Không có chunks trong law_id: 03/2013/TTLT-TANDTC-VKSNDTC
Không có chunks trong law_id: 03/2013/TTLT-TANDTC-VKSNDTC
Không có chunks trong law_id: 03/2013/TTLT-TANDTC-VKSNDTC
Không có chunks trong law_id: 03/2013/TTLT-TANDTC-VKSNDTC
Không có chunks trong law_id: 03/2013/TTLT-TANDTC-VKSNDTC
Không có chunks trong law_id: 03/2013/TTLT-TANDTC-VKSNDTC
Không có chunks trong law_id: 03/2013/TTLT-TANDTC-VKSNDTC
Không có chunks trong law_id: 03/2013/TTLT-TANDTC-VKSNDTC
Không có chunks trong law_id: 03/2013/TTLT-TANDTC-VKSNDTC
Không có chunks trong law_id: 03/2013/TTLT-TANDTC-VKSNDTC
Không có chunks trong law_id: 03/2013/TTLT-TANDTC-VKSNDTC
Không có chunks trong law_id: 03/2013/TTLT-TANDTC-VKSNDTC
Không có chunks trong law_id: 03/2013/TTLT-TANDTC-VKSNDTC
Không có chunks trong law_id: 03/2013/TTLT-TANDTC-VKSNDTC
15089
Không có chunks trong law_id: 590/QĐ-VKSTC-V3
Không có chunks trong law_id: 590/QĐ-VKSTC-V3
Không có chunks trong law_id: 590/QĐ-VKSTC-V3
Không có chunks trong law_id: 590/QĐ-VKSTC-V3
Không có chunks trong law_id: 590/QĐ-VKSTC-V3
Không có chunks trong law_id: 590/QĐ-VKSTC-V3
Không có chunks trong law_id: 590/QĐ-VKSTC-V3
Không có chunks trong law_id: 590/QĐ-VKSTC-V3
Không có chunks trong law_id: 590/QĐ-VKSTC-V3
Không có chunks trong law_id: 590/QĐ-VKSTC-V3
Không có chunks trong law_id: 590/QĐ-VKSTC-V3
Không có chunks trong law_id: 590/QĐ-VKSTC-V3
Không có chunks trong law_id: 386/2016/QĐ-TANDTC
Không có chunks trong law_id: 386/2016/QĐ-TANDTC
Không có chunks trong law_id: 386/2016/QĐ-TANDTC
Không có chunks trong law_id: 386/2016/QĐ-TANDTC
15508
15509
15510
15611
15616
15644
15653
15672
15678
15709
15722
15731
15732
15733
16027
16028
16029
16030
16031
16032
16034
16035
16036
16037
16038
16040
16045
16046
16051
16098
16099
16100
16101
16102
16103
16104
16105
16107
16108
16143
16144
16145
16156
16356
16386
16552
16681
16682
16695
16733
16734
16735
16736
16737
16738
16739
16740
16741
16742
16743
16744
16783
16795
16796
16797
16798
16824
17004
17005
17006
17009
17035
17036
17037
17234
17325
17326
17327
17428
17429
17430
17533
17649
17650
17651
17652
17653
17654
17655
17656
17657
17658
17659
17660
17661
17662
17663
17664
17665
17666
17667
17668
17669
17670
17671
17672
17673
17674
17675
17676
17677
17678
17679
17680
17681
17682
17683
17684
17685
17686
17687
17688
17689
17690
17691
17692
17693
17694
17695
17696
17697
17698
17699
17700
17701
17702
17703
17704
17705
17706
17707
17708
17709
17710
17711
17712
17713
17714
17715
17716
17717
17718
17719
17720
17721
17722
17723
17724
17725
17726
17727
17728
17729
17730
17731
17732
17733
17734
17735
17736
17737
17738
17739
17740
17741
17742
17743
17744
17745
17746
17747
17748
17749
17750
17751
17752
17753
17754
17755
17756
17757
17758
17759
17760
17761
17762
17763
17764
17765
17766
17767
17768
17769
17770
17771
17772
17773
17774
17775
17776
17777
17778
17779
17780
17781
17782
17783
18288
18435
18436
18437
18439
18440
18441
18442
18443
18444
18445
18447
18448
18449
18450
18451
18452
18453
18454
18455
18457
18459
18460
18461
18462
18463
18465
18466
18467
18469
18470
18471
18472
18473
18474
18475
18476
18477
18478
18479
18481
18486
18487
18673
19063
19064
19065
19224
Không có chunks trong law_id: 46/2020/TT-BGDĐT
Không có chunks trong law_id: 46/2020/TT-BGDĐT
Không có chunks trong law_id: 46/2020/TT-BGDĐT
Không có chunks trong law_id: 46/2020/TT-BGDĐT
19772
20286
20287
20288
21351
21548
21608
Không có chunks trong law_id: 1332/QĐ-BGTVT
Không có chunks trong law_id: 1332/QĐ-BGTVT
Không có chunks trong law_id: 1332/QĐ-BGTVT
Không có chunks trong law_id: 1332/QĐ-BGTVT
Không có chunks trong law_id: 1332/QĐ-BGTVT
Không có chunks trong law_id: 1332/QĐ-BGTVT
Không có chunks trong law_id: 1332/QĐ-BGTVT
Không có chunks trong law_id: 1332/QĐ-BGTVT
Không có chunks trong law_id: 1332/QĐ-BGTVT
Không có chunks trong law_id: 1332/QĐ-BGTVT
Không có chunks trong law_id: 1332/QĐ-BGTVT
Không có chunks trong law_id: 1332/QĐ-BGTVT
Không có chunks trong law_id: 1332/QĐ-BGTVT
Không có chunks trong law_id: 1332/QĐ-BGTVT
Không có chunks trong law_id: 1332/QĐ-BGTVT
Không có chunks trong law_id: 1332/QĐ-BGTVT
Không có chunks trong law_id: 1332/QĐ-BGTVT
Không có chunks trong law_id: 1332/QĐ-BGTVT
Không có chunks trong law_id: 1332/QĐ-BGTVT
Không có chunks trong law_id: 1332/QĐ-BGTVT
Không có chunks trong law_id: 1332/QĐ-BGTVT
Không có chunks trong law_id: 1332/QĐ-BGTVT
Không có chunks trong law_id: 1332/QĐ-BGTVT
Không có chunks trong law_id: 1332/QĐ-BGTVT
Không có chunks trong law_id: 1332/QĐ-BGTVT
Không có chunks trong law_id: 1332/QĐ-BGTVT
Không có chunks trong law_id: 1332/QĐ-BGTVT
21712
21819
21980
21982
22116
22126
22213
22214
22291
22292
22293
22741
Không có chunks trong law_id: 1919/QĐ-BTC
Không có chunks trong law_id: 1919/QĐ-BTC
Không có chunks trong law_id: 1919/QĐ-BTC
Không có chunks trong law_id: 1919/QĐ-BTC
Không có chunks trong law_id: 1919/QĐ-BTC
Không có chunks trong law_id: 1919/QĐ-BTC
Không có chunks trong law_id: 1919/QĐ-BTC
23241
23247
23254
23458
Không có chunks trong law_id: 188/QĐ-TCHQ
Không có chunks trong law_id: 188/QĐ-TCHQ
Không có chunks trong law_id: 188/QĐ-TCHQ
23647
23676
23763
23870
23872
24394
24395
24396
24397
24398
24399
24663
24665
24689
24708
24710
24756
24757
24786
24939
24940
24941
24942
24943
24944
24945
24946
24947
24948
24949
24950
24951
24952
24953
24954
24955
24956
24957
24958
24959
24960
24961
24962
24963
24964
24965
24966
24967
24968
24969
24970
24971
24972
24973
24974
24975
24976
24977
24978
24979
24980
24981
24982
24983
24984
24985
24986
24987
24988
24989
24990
24991
24992
24993
24994
24995
24996
24997
24998
24999
25000
25001
25002
25003
25004
25005
25006
25007
25008
25009
25657
25991
26102
26103
26104
26105
26106
26466
26623
26941
26942
26943
26944
26945
26946
27145
27590
27678
27679
27689
27691
27698
27903
28292
28293
28294
28295
28296
28298
28299
28430
28436
28594
Không có chunks trong law_id: 06/2012/TT-BNV
Không có chunks trong law_id: 06/2012/TT-BNV
Không có chunks trong law_id: 06/2012/TT-BNV
Không có chunks trong law_id: 06/2012/TT-BNV
Không có chunks trong law_id: 06/2012/TT-BNV
Không có chunks trong law_id: 06/2012/TT-BNV
Không có chunks trong law_id: 06/2012/TT-BNV
Không có chunks trong law_id: 06/2012/TT-BNV
Không có chunks trong law_id: 06/2012/TT-BNV
Không có chunks trong law_id: 06/2012/TT-BNV
Không có chunks trong law_id: 06/2012/TT-BNV
Không có chunks trong law_id: 06/2012/TT-BNV
Không có chunks trong law_id: 06/2012/TT-BNV
Không có chunks trong law_id: 06/2012/TT-BNV
Không có chunks trong law_id: 06/2012/TT-BNV
Không có chunks trong law_id: 06/2012/TT-BNV
Không có chunks trong law_id: 06/2012/TT-BNV
Không có chunks trong law_id: 06/2012/TT-BNV
Không có chunks trong law_id: 06/2012/TT-BNV
Không có chunks trong law_id: 06/2012/TT-BNV
Không có chunks trong law_id: 06/2012/TT-BNV
28952
28953
28954
29040
29041
29042
29043
29044
29045
29046
29047
29048
29049
29050
29051
Không có chunks trong law_id: 70/2018/QH14
Không có chunks trong law_id: 70/2018/QH14
Không có chunks trong law_id: 70/2018/QH14
Không có chunks trong law_id: 70/2018/QH14
Không có chunks trong law_id: 70/2018/QH14
29396
29397
29398
29399
29400
29401
29553
29693
29695
29820
30134
30135
30136
30164
30748
31595
31596
31597
32261
32706
32888
33051
33052
33053
33054
33055
33056
33163
33251
33252
33253
33271
33343
33344
33345
33630
34070
34071
34072
34073
34272
34345
34346
34347
34879
34880
34928
35019
35024
35026
35027
35091
35093
35209
35210
35211
35369
35370
35371
35424
35425
35426
35848
35932
35933
35934
35935
35936
35937
35938
35939
35940
35941
35942
35943
35944
35945
35946
35947
35948
35949
35950
35951
35952
35953
35954
35955
35956
35957
35958
35959
35960
35961
35962
35963
35964
35965
35966
35967
35968
35969
35970
35971
35972
35973
35974
35975
35976
35977
35978
35979
35980
35981
35982
35983
35984
35985
35986
35987
35988
35989
35990
35991
35992
35993
35994
35995
35996
36050
36054
36056
36057
36059
36060
36061
36062
36063
36064
36190
36191
36192
36193
36194
36195
36196
36197
36198
36273
36274
36275
36276
36277
36278
36279
36280
36393
36707
36709
36710
36747
36828
36829
36830
36831
36832
36833
36841
36928
37023
37087
37131
Không có chunks trong law_id: 963/QĐ-BCT
Không có chunks trong law_id: 963/QĐ-BCT
Không có chunks trong law_id: 963/QĐ-BCT
Không có chunks trong law_id: 963/QĐ-BCT
Không có chunks trong law_id: 963/QĐ-BCT
37666
38010
38073
38074
38075
38076
38077
38078
38079
38080
38081
38082
38083
38084
38085
38086
38087
38088
38089
38090
38091
38092
38093
38094
38095
38096
38097
38098
38099
38100
38101
38102
38103
38104
38105
38106
38107
38108
38109
38110
38111
38112
38113
38114
38115
38116
38117
38118
38119
38120
38121
38122
38123
38124
38125
38126
38127
38128
38129
38130
38131
38132
38133
38134
38135
38136
38137
38138
38139
38140
38141
38142
38143
38144
38145
38146
38147
38148
38149
38150
38151
38152
38153
38154
38155
38156
38157
38158
38159
38160
38161
38162
38163
38164
38165
38166
38167
38168
38169
38170
38171
38172
38173
38174
38175
38176
38177
38178
38179
38180
38181
38182
38183
38184
38185
38186
38187
38188
38189
38190
38191
38192
38193
38194
38195
38196
38197
38198
38199
38200
38201
38202
38203
38204
38205
38206
38321
38322
38323
38324
38325
38326
38330
38331
38332
38333
38335
38339
38342
38351
38352
38353
38356
38357
38358
38360
38361
38362
38363
38364
38366
38367
38369
38371
38372
38374
38376
38377
38378
38379
38380
38382
38383
38385
38388
38390
38391
38392
38393
38394
38395
38396
38397
38398
38399
38400
38401
38402
38403
38405
38407
38408
38409
38410
38411
38412
38413
38414
38415
38416
38417
38418
38419
38421
38422
38425
38427
38428
38430
38431
38433
38434
38435
38436
38437
38438
38440
38442
38445
38447
38448
38449
38450
38451
38452
38453
38454
38455
38456
38457
38460
38462
38466
38467
38469
38470
38471
38472
38473
38474
38475
38476
38478
38481
38482
38483
38484
38485
38486
38488
38489
38490
38491
38492
38493
38498
38499
38500
38503
38504
38505
38506
38507
38508
38509
38510
38512
38513
38514
38515
38516
38517
38519
38520
38521
38522
38523
38524
38525
38529
38530
38536
38540
38542
38543
38544
38545
38546
38547
38549
38550
38552
38553
38554
38555
38556
38557
38558
38563
38564
38565
38568
38569
38570
38571
38572
38573
38574
38575
38576
38577
38578
38580
38581
38582
38583
38584
38585
38586
38587
38588
38589
38590
38591
38592
38598
38848
38852
38983
39326
39327
39328
39417
39452
39453
39454
39493
39494
39495
39496
39497
39498
39499
39672
39673
39674
39725
39747
39748
39749
39835
39836
39837
39838
39839
39840
39991
40038
40039
40040
40041
40042
40043
40044
40045
Không có chunks trong law_id: 742/QĐ-BHXH
Không có chunks trong law_id: 742/QĐ-BHXH
Không có chunks trong law_id: 742/QĐ-BHXH
Không có chunks trong law_id: 742/QĐ-BHXH
Không có chunks trong law_id: 742/QĐ-BHXH
Không có chunks trong law_id: 742/QĐ-BHXH
Không có chunks trong law_id: 742/QĐ-BHXH
Không có chunks trong law_id: 742/QĐ-BHXH
Không có chunks trong law_id: 742/QĐ-BHXH
Không có chunks trong law_id: 742/QĐ-BHXH
Không có chunks trong law_id: 742/QĐ-BHXH
Không có chunks trong law_id: 742/QĐ-BHXH
Không có chunks trong law_id: 742/QĐ-BHXH
Không có chunks trong law_id: 742/QĐ-BHXH
Không có chunks trong law_id: 742/QĐ-BHXH
40247
40310
40311
40312
40313
40314
40315
40316
40347
40349
40350
40351
40353
40361
40362
40363
40439
40440
40441
40442
40535
40536
40537
40538
41005
41008
41009
41010
41203
41438
41439
41440
41645
41646
41647
41648
41649
41650
41651
41848
41849
41861
41864
41867
41868
41871
41878
41883
41892
41893
41897
41946
41947
41948
41949
41950
41951
42088
42089
42147
42191
42193
42194
42195
43026
43027
43028
43058
43528
43529
43532
43533
43534
43539
43540
43541
43542
43544
Không có chunks trong law_id: 53/2012/TT-BGTVT
Không có chunks trong law_id: 53/2012/TT-BGTVT
Không có chunks trong law_id: 53/2012/TT-BGTVT
Không có chunks trong law_id: 53/2012/TT-BGTVT
Không có chunks trong law_id: 53/2012/TT-BGTVT
Không có chunks trong law_id: 53/2012/TT-BGTVT
Không có chunks trong law_id: 53/2012/TT-BGTVT
Không có chunks trong law_id: 53/2012/TT-BGTVT
Không có chunks trong law_id: 53/2012/TT-BGTVT
Không có chunks trong law_id: 53/2012/TT-BGTVT
Không có chunks trong law_id: 53/2012/TT-BGTVT
Không có chunks trong law_id: 53/2012/TT-BGTVT
Không có chunks trong law_id: 53/2012/TT-BGTVT
Không có chunks trong law_id: 53/2012/TT-BGTVT
Không có chunks trong law_id: 53/2012/TT-BGTVT
Không có chunks trong law_id: 53/2012/TT-BGTVT
Không có chunks trong law_id: 53/2012/TT-BGTVT
Không có chunks trong law_id: 53/2012/TT-BGTVT
Không có chunks trong law_id: 53/2012/TT-BGTVT
Không có chunks trong law_id: 53/2012/TT-BGTVT
Không có chunks trong law_id: 53/2012/TT-BGTVT
Không có chunks trong law_id: 53/2012/TT-BGTVT
43702
43703
43786
43787
43800
43801
43841
43842
43844
43845
43846
43847
43848
43849
43850
43851
43852
43853
43895
43995
44053
44111
44118
44120
44127
44128
44129
44130
44131
44133
44134
44142
44150
44178
44447
44448
44449
44457
44461
44462
44463
44464
44465
44466
44612
44613
44614
44615
44642
44657
44690
44730
44765
44826
44854
44923
44925
45492
45584
45587
45604
45606
45607
45608
45609
45610
45611
45913
45915
46087
46088
46089
46090
46091
Không có chunks trong law_id: 78-QĐ/TW
Không có chunks trong law_id: 78-QĐ/TW
Không có chunks trong law_id: 78-QĐ/TW
Không có chunks trong law_id: 78-QĐ/TW
Không có chunks trong law_id: 78-QĐ/TW
46104
46105
46106
46107
46108
46109
46154
46159
46160
46161
46162
46163
Không có chunks trong law_id: 166-QĐ/TW
Không có chunks trong law_id: 166-QĐ/TW
Không có chunks trong law_id: 166-QĐ/TW
Không có chunks trong law_id: 166-QĐ/TW
Không có chunks trong law_id: 166-QĐ/TW
Không có chunks trong law_id: 166-QĐ/TW
Không có chunks trong law_id: 230/QĐ-UBDT
Không có chunks trong law_id: 230/QĐ-UBDT
Không có chunks trong law_id: 230/QĐ-UBDT
Không có chunks trong law_id: 230/QĐ-UBDT
Không có chunks trong law_id: 230/QĐ-UBDT
46515
46571
46572
46699
46700
46701
46702
46703
46704
46711
46712
46713
46800
46801
47199
47202
47203
47954
47965
47966
47967
47970
47971
Không có chunks trong law_id: 2196/QĐ-BGTVT
Không có chunks trong law_id: 2196/QĐ-BGTVT
Không có chunks trong law_id: 2196/QĐ-BGTVT
Không có chunks trong law_id: 2196/QĐ-BGTVT
Không có chunks trong law_id: 2196/QĐ-BGTVT
Không có chunks trong law_id: 2196/QĐ-BGTVT
48155
48156
48157
48158
48159
48232
48233
48363
48364
48365
48440
48441
48442
48443
48444
48445
48446
48447
48456
48457
48458
48459
48460
48513
48544
48549
48550
48551
48552
48719
Không có chunks trong law_id: 32/2018/QĐ-TTg
Không có chunks trong law_id: 32/2018/QĐ-TTg
Không có chunks trong law_id: 32/2018/QĐ-TTg

In [17]:
df[df['titles'].apply(lambda x: not x)]

,id,law_id,aid,content_Article,titles
1175,44,31/NQ-CP,1175,Chính phủ thống nhất đánh giá: Trong bối cảnh\...,[]
1176,44,31/NQ-CP,1176,\t\ta) Khẩn trương hoàn thành việc xây dựng: B...,[]
1177,44,31/NQ-CP,1177,\t\ta) Thực hiện chính sách tài khóa mở rộng h...,[]
1178,44,31/NQ-CP,1178,\t\ta) Điều hành các công cụ chính sách tiền t...,[]
1179,44,31/NQ-CP,1179,"\t\ta) Rà soát, thúc đẩy phát triển và cơ cấu ...",[]
...,...,...,...,...,...
59282,2133,30/2024/NĐ-CP,59282,"Các Bộ trưởng, Thủ trưởng cơ quan ngang bộ, Th...",[]
59578,2150,22/2024/TT-BTC,59578,"1. Sửa đổi, bổ sung điểm 3 Phụ lục số 01/ĐKHN,...",[]
59579,2150,22/2024/TT-BTC,59579,1. Thay thế cụm từ “Giấy CMND/Hộ chiếu số:...c...,[]
59580,2150,22/2024/TT-BTC,59580,"1. Sửa đổi, bổ sung điểm 3 Phụ lục số 06 ban h...",[]
59581,2150,22/2024/TT-BTC,59581,1. Thông tư này có hiệu lực kể từ ngày 1 tháng...,[]

In [18]:
df.to_parquet("data/law_corpus_with_titles.parquet",
    index=False,
    compression="zstd",
    engine="pyarrow"
)